using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;

namespace Lox.SourceGenerator
{
    [Generator]
    public class SourceGenerator : ISourceGenerator
    {
        private StringBuilder _codeSB = new StringBuilder();

        private string _baseName = "Expr";

        private List<string> _dsp = new List<string>()
        {
            "Binary   : Expr left, Token loxOperator, Expr right",
            "Grouping : Expr expression",
            "Literal  : Object value",
            "Unary    : Token loxOperator, Expr right"
        };
        private void DefineVisitor(string baseName, List<string> types)
        {
            _codeSB.Append($@"
        internal interface Visitor<R>
        {{
");
            for (int i = 0; i < types.Count; i++)
            {
                string typeName = types[i].Split(':')[0].Trim();
                _codeSB.Append($@"
            public R? Visit{typeName}{baseName}({typeName} {baseName.ToLower()});
");
            }

            _codeSB.Append($@"
        }}
");
        }
        private void DefineType(string className, string fieldList)
        {
            _codeSB.Append($@"
        internal class {className} : {_baseName}
        {{
            // Constructor.
            public {className} ({fieldList})
            {{
        ");
            // Store parameters in fields.
            string[] fields = fieldList.Split(',');
            foreach (string field in fields)
            {
                List<string> splitField = field.Split(' ').ToList();
                splitField.RemoveAll(item =>
                {
                    return String.IsNullOrEmpty(item);
                });

                string name = splitField[1];
                _codeSB.Append($@"
                this.{name} = {name};
        ");
            }
            _codeSB.Append($@"
            }}
        ");

            // Visitor pattern.
            _codeSB.Append($@"
            internal override R Accept<R>(Visitor<R> visitor)
            {{
                return visitor.Visit{className}{_baseName}(this);
            }}");

            // Fields.
            foreach (string field in fields)
            {
                List<string> splitField = field.Split(' ').ToList();
                splitField.RemoveAll(item =>
                {
                    return String.IsNullOrEmpty(item);
                });

                string name = splitField[1];
                string type = splitField[0];
                _codeSB.Append($@"

            internal {type} {name};
        ");
            }

            _codeSB.Append($@"
        }}
        ");
        }
        private void DefineAst()
        {
            _codeSB.Append($@"// <auto-generated/>
using System;
//using System.Collections.Generic;
using Interpreter;
namespace LoxGenerated
{{  
    public abstract class {_baseName}
    {{
");
            DefineVisitor(_baseName, _dsp);
            for (int i = 0; i < _dsp.Count; i++)
            {
                string className = _dsp[i].Split(':')[0].Trim();
                string fields = _dsp[i].Split(':')[1];
                DefineType(className, fields);
            }

            _codeSB.Append($@"
        internal abstract R Accept<R>(Visitor<R> visitor);
    }}
}}
");
        }
        public void Execute(GeneratorExecutionContext context)
        {
            _codeSB.Clear();
            DefineAst();
            context.AddSource("Expr.g.cs", SourceText.From(_codeSB.ToString(), Encoding.UTF8));
        }

        public void Initialize(GeneratorInitializationContext context)
        {
//#if DEBUG
//            if (!Debugger.IsAttached)
//            {
//                Debugger.Launch();
//            }
//#endif 
//            Debug.WriteLine("Initalize code generator");
        }
    }
}
